/* eslint-disable */
export default async () => {
    const t = {
        ["./utils/enum/user.enum"]: await import("./utils/enum/user.enum"),
        ["./modules/apps/auth/viewmodel/login.viewmodel"]: await import("./modules/apps/auth/viewmodel/login.viewmodel"),
        ["./modules/apps/example/controllers/viewmodel/user.viewmodel"]: await import("./modules/apps/example/controllers/viewmodel/user.viewmodel"),
        ["./modules/apps/example/controllers/viewmodel/role.viewmodel"]: await import("./modules/apps/example/controllers/viewmodel/role.viewmodel")
    };
    return { "@nestjs/swagger": { "models": [[import("./modules/apps/auth/request/login.request"), { "LoginRequest": { username: { required: true, type: () => String }, password: { required: true, type: () => String } } }], [import("./modules/apps/auth/viewmodel/login.viewmodel"), { "LoginVm": { expiresIn: { required: true, type: () => Number, example: "asdasdasd" }, token: { required: true, type: () => String, example: "50" } } }], [import("./modules/apps/example/controllers/viewmodel/user.viewmodel"), { "UserVm": { id: { required: true, type: () => Number }, name: { required: true, type: () => String }, code: { required: true, type: () => String }, email: { required: true, type: () => String, description: "@example fauzifadhi@gmail.com" }, gender: { required: true, enum: t["./utils/enum/user.enum"].EGender }, nationality: { required: false, type: () => String, default: "ID" }, roles: { required: true, type: () => [RoleVm] } } }], [import("./modules/apps/example/controllers/request/create-user.request"), { "CreateUserReq": { username: { required: true, type: () => String, minLength: 8, maxLength: 20 }, password: { required: true, type: () => String }, name: { required: true, type: () => String }, phone: { required: false, type: () => String }, email: { required: true, type: () => String }, roleId: { required: true, type: () => Number } } }], [import("./modules/apps/example/controllers/request/create-role.request"), { "CreateRoleReq": { name: { required: true, type: () => String } } }], [import("./modules/apps/example/controllers/viewmodel/role.viewmodel"), { "RoleVm": { id: { required: true, type: () => Number }, name: { required: true, type: () => String } } }]], "controllers": [[import("./app.controller"), { "AppController": { "getHello": { type: String } } }], [import("./modules/apps/auth/auth.controller"), { "AuthController": { "login": { type: t["./modules/apps/auth/viewmodel/login.viewmodel"].LoginVm } } }], [import("./modules/apps/example/controllers/user.controller"), { "UserController": { "getUser": { type: t["./modules/apps/example/controllers/viewmodel/user.viewmodel"].UserVm }, "createUser": { type: t["./modules/apps/example/controllers/viewmodel/user.viewmodel"].UserVm } } }], [import("./modules/apps/example/controllers/role.controller"), { "RoleController": { "createUser": { type: t["./modules/apps/example/controllers/viewmodel/role.viewmodel"].RoleVm } } }]] } };
};